Models/Validation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ClientValidation.Models
{
    public class Validation
    {
        //entered data validtions//
       [Required(ErrorMessage = "Please enter Name.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter Phone No.")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.")]
        public string Phone { get; set; }

         [Required(ErrorMessage = "Please enter Phone No.")]
         //[RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail is not valid")]

         [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}" +
                            @"\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\" +
                            @".)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$",
                            ErrorMessage = "Email is not valid")]
        public string Email { get; set; }

        [Required(ErrorMessage = "- Select item -")]
         public string Gender { get; set; }

        public string Upload_files { get; set; }
    }
}

Controllers/ValidationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientValidation.Models;
using System.IO; 

namespace ClientValidation.Controllers
{
    public class ValidationController : Controller
    {
        //
        // GET: /Validation/
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Index(Validation model, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //bind the model attributes to send it to view//
                ViewBag.Name = model.Name;
                ViewBag.Phone = model.Phone;
                ViewBag.Email = model.Email;
                ViewBag.Gender = model.Gender;

                string _FileName = Path.GetFileName(upload.FileName);
                string _path = Path.Combine(Server.MapPath("~/Images"), _FileName);
                upload.SaveAs(_path);
                
                ViewBag.Message = "File Uploaded Successfully!!";
                //clear the model once data is submitted// 
                ModelState.Clear();
                //on click of submit, show the text message// 
                TempData["Success Message"] = "data saved successfully";

                return View();


                
            }
            return View(model); 
            
        }
        
	}
}

Views/Validation/Index.cshtml
@model ClientValidation.Models.Validation
@{
    ViewBag.Title = "Index";
}

<h2>Enter the details</h2>

@*@if (ViewData.ModelState.IsValid)
{
    if (@ViewBag.Name != null)
    {
        <b>
            Name : @ViewBag.Name<br />
            Email : @ViewBag.Email
        </b>
    }
}*@

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    
    <fieldset >
        
        <div>
            @Html.LabelFor(model => model.Name ) :
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name) 
        </div><br />


        <div>
            @Html.LabelFor(model => model.Phone) :
            @Html.EditorFor(model => model.Phone)
            @Html.ValidationMessageFor(model => model.Phone)
        </div><br />


        <div>
            @Html.LabelFor(model => model.Email) :
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div><br />
        
        <div>
            @Html.LabelFor(model => model.Gender)
            <select>
                <option>Select Gender</option>
                <option>Male</option>
                <option>Female</option>
            </select>
            @Html.ValidationMessageFor(model => model.Gender)
        </div>

        <div>
            @Html.LabelFor(model => model.Upload_files)
            @using (Html.BeginForm("Index", "Validation", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
            <input type="file" name="file" />
            
            }
        </div>
        <br /><br />
        <p>
            <input type="submit" value="submit" id="myForm" />
        </p>
    </fieldset>
    
}


@*<script>
    function submitForm()
    {
        var frm = document.getElementById('submit')[0];
        frm.submit(); // Submit the form
        frm.reset();  // Reset all form data
        return false;


    }
</script>*@

<h3 style="color:red">@TempData["Success Message"]</h3>
@*<script>
    var form = document.getElementById("myForm");
    form.reset();
</script>*@